# Generated by Django 2.0.7 on 2018-08-19 11:58

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('postgroups', '0002_remove_postgroup_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
