# Generated by Django 2.0.7 on 2018-08-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgroups', '0004_postgroup_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='teaser',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
