# Generated by Django 2.0.7 on 2018-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgroups', '0005_postgroup_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgroup',
            name='teaser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
