# Generated by Django 2.0.7 on 2018-08-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='teaser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
